version: "3.7"

services:
  api:
    build: .
    secrets:
      - jwt_token
    environment:
      DB_HOST: rethinkdb
      DEBUG_LOGGING: "true"
    tty: true
    volumes:
      - .:/app
      - /app/node_modules

  rethinkdb:
    image: rethinkdb
    ports:
      - 8181:8080
      - 28115:28015

secrets:
  jwt_token: 
    file: ./package.json