version: "3.7"

services:
  api:
    build: .
    secrets:
      - jwt_token
    environment:
      DB_HOST: rethinkdb
      DEBUG_LOGGING: "true"
      APP_PUBLIC_URL: https://sso.test
    tty: true
    volumes:
      - .:/app
      - /app/node_modules

  rethinkdb:
    image: rethinkdb
    ports:
      - 8080:8080
      - 28015:28015

secrets:
  jwt_token: 
    file: ./package.json